language: cpp
sudo: required
dist: trusty
branches:
  only:
    - master

osx_image: xcode8
os:
  - linux
  - osx

env:
  - CONFIG=Release
  - CONFIG=Debug

compiler:
  - clang
  - gcc

before_install:
  - QT_VERSION_MM=56
  - QT_VERSION_FULL=562-trusty
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
    sudo apt-add-repository --yes ppa:beineri/opt-qt$QT_VERSION_FULL
      && sudo apt-get update -qq
      && sudo apt-get install -y uwsgi uuid-dev libcap-dev libzmq3-dev libpcre3-dev zlib1g-dev libssl-dev
      && sudo apt-get install -y clearsilver-dev 
      && sudo apt-get install -qq qt${QT_VERSION_MM}base qt${QT_VERSION_MM}tools
      && export CMAKE_PREFIX_PATH=/opt/qt${QT_VERSION_MM};
    fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then
      brew update;
      brew outdated cmake || brew upgrade cmake;
      brew install qt5;
      export CMAKE_PREFIX_PATH=$(brew --prefix qt5);
    fi

before_script:
   - mkdir build
   - cd build
   - cmake .. -DCMAKE_BUILD_TYPE=$CONFIG -DENABLE_MAINTAINER_CFLAGS=on

script:
   - cmake --build . --config $CONFIG
   - ctest --output-on-failure

notifications:
  email:
    recipients:
      - dantti12@gmail.com

