version: '{build}'

branches:
  only:
    - master

shallow_clone: true
clone_depth: 1

init:
  - git config --global core.autocrlf input

clone_folder: c:\dev\cutelyst

environment:
  matrix:
  - CMAKE_GENERATOR: "Ninja"
    QT5: C:\Qt\5.9\msvc2015
    PLATFORM: X86
    VSVER: 14
    ENABLE_MAINTAINER_CFLAGS: off
  - CMAKE_GENERATOR: "Ninja"
    QT5: C:\Qt\5.9\msvc2015_64
    PLATFORM: X64
    VSVER: 14
    ENABLE_MAINTAINER_CFLAGS: off
  - CMAKE_GENERATOR: "Visual Studio 14"
    QT5: C:\Qt\5.9\msvc2015
    PLATFORM: X86
    VSVER: 14
    ENABLE_MAINTAINER_CFLAGS: off
  - CMAKE_GENERATOR: "Visual Studio 14 Win64"
    QT5: C:\Qt\5.9\msvc2015_64
    PLATFORM: X64
    VSVER: 14
    ENABLE_MAINTAINER_CFLAGS: off
  - CMAKE_GENERATOR: "Visual Studio 15 2017 Win64"
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    QT5: C:\Qt\5.9\msvc2017_64
    PLATFORM: X64
    VSVER: 17
    ENABLE_MAINTAINER_CFLAGS: off
  - CMAKE_GENERATOR: "MinGW Makefiles"
    QT5: C:\Qt\5.9\mingw53_32
    MINGW_PATH: C:\Qt\Tools\mingw530_32
    ENABLE_MAINTAINER_CFLAGS: on

  - CMAKE_GENERATOR: "Ninja"
    QT5: C:\Qt\5.8\msvc2015
    PLATFORM: X86
    VSVER: 14
    ENABLE_MAINTAINER_CFLAGS: off
  - CMAKE_GENERATOR: "Ninja"
    QT5: C:\Qt\5.8\msvc2015_64
    PLATFORM: X64
    VSVER: 14
    ENABLE_MAINTAINER_CFLAGS: off
  - CMAKE_GENERATOR: "Visual Studio 14"
    QT5: C:\Qt\5.8\msvc2015
    PLATFORM: X86
    VSVER: 14
    ENABLE_MAINTAINER_CFLAGS: off
  - CMAKE_GENERATOR: "Visual Studio 14 Win64"
    QT5: C:\Qt\5.8\msvc2015_64
    PLATFORM: X64
    VSVER: 14
    ENABLE_MAINTAINER_CFLAGS: off
  - CMAKE_GENERATOR: "MinGW Makefiles"
    QT5: C:\Qt\5.8\mingw53_32
    MINGW_PATH: C:\Qt\Tools\mingw530_32
    ENABLE_MAINTAINER_CFLAGS: on

  - CMAKE_GENERATOR: "Ninja"
    QT5: C:\Qt\5.7\msvc2015
    PLATFORM: X86
    VSVER: 14
    ENABLE_MAINTAINER_CFLAGS: off
  - CMAKE_GENERATOR: "Ninja"
    QT5: C:\Qt\5.7\msvc2015_64
    PLATFORM: X64
    VSVER: 14
    ENABLE_MAINTAINER_CFLAGS: off
  - CMAKE_GENERATOR: "Visual Studio 14"
    QT5: C:\Qt\5.7\msvc2015
    PLATFORM: X86
    VSVER: 14
    ENABLE_MAINTAINER_CFLAGS: off
  - CMAKE_GENERATOR: "Visual Studio 14 Win64"
    QT5: C:\Qt\5.7\msvc2015_64
    PLATFORM: X64
    VSVER: 14
    ENABLE_MAINTAINER_CFLAGS: off
  - CMAKE_GENERATOR: "MinGW Makefiles"
    QT5: C:\Qt\5.7\mingw53_32
    MINGW_PATH: C:\Qt\Tools\mingw530_32
    ENABLE_MAINTAINER_CFLAGS: on

  - CMAKE_GENERATOR: "Ninja"
    QT5: C:\Qt\5.6\msvc2015
    PLATFORM: X86
    VSVER: 14
    ENABLE_MAINTAINER_CFLAGS: off
  - CMAKE_GENERATOR: "Ninja"
    QT5: C:\Qt\5.6\msvc2015_64
    PLATFORM: X64
    VSVER: 14
    ENABLE_MAINTAINER_CFLAGS: off
  - CMAKE_GENERATOR: "Visual Studio 14"
    QT5: C:\Qt\5.6\msvc2015
    PLATFORM: X86
    VSVER: 14
    ENABLE_MAINTAINER_CFLAGS: off
  - CMAKE_GENERATOR: "Visual Studio 14 Win64"
    QT5: C:\Qt\5.6\msvc2015_64
    PLATFORM: X64
    VSVER: 14
    ENABLE_MAINTAINER_CFLAGS: off
#  - CMAKE_GENERATOR: "NMake Makefiles JOM"
#    QT5: C:\Qt\5.6\msvc2015
#    PLATFORM: X86
#    VSVER: 14
#    ENABLE_MAINTAINER_CFLAGS: off
#  - CMAKE_GENERATOR: "NMake Makefiles JOM"
#    QT5: C:\Qt\5.6\msvc2015_64
#    PLATFORM: X64
#    VSVER: 14
#    ENABLE_MAINTAINER_CFLAGS: off
  - CMAKE_GENERATOR: "MinGW Makefiles"
    QT5: C:\Qt\5.6\mingw49_32
    MINGW_PATH: C:\Qt\Tools\mingw492_32
    ENABLE_MAINTAINER_CFLAGS: on

before_build:
  - set PATH=C:\cygwin\bin;%QT5%\bin;c:\dev\cutelyst\build\Cutelyst;%PATH%
  - sed -i "s|std::equal(b, e, lb)|std::equal(b, e,\n#if defined(Q_CC_MSVC)\nstdext::make_unchecked_array_iterator(lb)\n#else\nlb\n#endif\n)|" %QT5%\include\QtCore\qlist.h
  - set PATH=%PATH:C:\cygwin\bin;=%
  - if "%CMAKE_GENERATOR%" == "MinGW Makefiles" set PATH=%MINGW_PATH%\bin;%PATH:C:\Program Files\Git\usr\bin;=%
  - if "%CMAKE_GENERATOR%" == "NMake Makefiles JOM" set PATH=C:\Qt\Tools\QtCreator\bin;%PATH%
  - if "%CMAKE_GENERATOR%" == "Ninja" cinst ninja
  - if "%CMAKE_GENERATOR%" == "Ninja" set PATH=C:\tools\ninja;%PATH%
  #- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

build:

build_script:
  - ps: $env:VSCOMNTOOLS=(Get-Content ("env:VS" + "$env:VSVER" + "0COMNTOOLS"))
  - if NOT "%CMAKE_GENERATOR%" == "MinGW Makefiles" echo "Using Visual Studio %VSVER%.0 at %VSCOMNTOOLS%"
  - if "%CMAKE_GENERATOR%" == "MinGW Makefiles" echo "Using MinGW"
  - if "%CMAKE_GENERATOR%" == "NMake Makefiles JOM" if "%PLATFORM%" == "X86" call "%VSCOMNTOOLS%\..\..\VC\vcvarsall.bat"
  - if "%CMAKE_GENERATOR%" == "NMake Makefiles JOM" if "%PLATFORM%" == "X64" "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64
  - if "%CMAKE_GENERATOR%" == "NMake Makefiles JOM" if "%PLATFORM%" == "X64" call "%VSCOMNTOOLS%\..\..\VC\vcvarsall.bat" x86_amd64
  - if "%CMAKE_GENERATOR%" == "Ninja" if "%PLATFORM%" == "X86" call "%VSCOMNTOOLS%\..\..\VC\vcvarsall.bat"
  - if "%CMAKE_GENERATOR%" == "Ninja" if "%PLATFORM%" == "X64" "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64
  - if "%CMAKE_GENERATOR%" == "Ninja" if "%PLATFORM%" == "X64" call "%VSCOMNTOOLS%\..\..\VC\vcvarsall.bat" x86_amd64
  - cd c:\dev\cutelyst
  - md build
  - cd build
  - cmake .. -G "%CMAKE_GENERATOR%" "-DCMAKE_PREFIX_PATH=%QT5%" "-DENABLE_MAINTAINER_CFLAGS=%ENABLE_MAINTAINER_CFLAGS%"
  - cmake --build . --config Debug
  - cmake --build . --config Release

test_script:
  - cmd: ctest --output-on-failure -C "Debug"
  - cmd: ctest --output-on-failure -C "Release"

